# Convert CSV to Excel with Color Coding
# Converts CSV files generated by Windows Autorun Analyzer to properly formatted Excel files

param(
    [Parameter(Mandatory=$true)]
    [string]$CsvPath,
    
    [Parameter(Mandatory=$false)]
    [string]$OutputPath = "",
    
    [Parameter(Mandatory=$false)]
    [switch]$Recursive,
    
    [Parameter(Mandatory=$false)]
    [switch]$Help
)

# Show help if requested
if ($Help) {
    Write-Host @"
CSV to Excel Converter for Windows Autorun Analyzer
==================================================

This script converts CSV files generated by the Windows Autorun Analyzer 
to properly formatted Excel files with color coding and analysis summary.

Usage:
  .\Convert-CSV-to-Excel.ps1 -CsvPath "path\to\file.csv"
  .\Convert-CSV-to-Excel.ps1 -CsvPath "path\to\file.csv" -OutputPath "path\to\output.xlsx"
  .\Convert-CSV-to-Excel.ps1 -CsvPath "C:\temp" -Recursive

Parameters:
  -CsvPath <string>    : Path to CSV file or directory containing CSV files
  -OutputPath <string> : Output path for Excel file (optional, auto-generated if not provided)
  -Recursive           : Process all CSV files in directory recursively
  -Help                : Show this help message

Examples:
  # Convert single CSV file
  .\Convert-CSV-to-Excel.ps1 -CsvPath "AutorunAnalysis_20250113_140657.csv"

  # Convert with custom output path
  .\Convert-CSV-to-Excel.ps1 -CsvPath "AutorunAnalysis_20250113_140657.csv" -OutputPath "C:\Reports\Analysis.xlsx"

  # Convert all CSV files in directory
  .\Convert-CSV-to-Excel.ps1 -CsvPath "C:\temp" -Recursive

"@
    exit 0
}

# Function to write status messages
function Write-Status {
    param($Message, $Color = "White")
    Write-Host "[$(Get-Date -Format 'HH:mm:ss')] $Message" -ForegroundColor $Color
}

# Function to check if ImportExcel module is available
function Test-ImportExcelModule {
    try {
        Import-Module ImportExcel -ErrorAction SilentlyContinue
        return $true
    } catch {
        return $false
    }
}

# Function to convert CSV to Excel with formatting
function Convert-CsvToExcel {
    param($CsvFile, $ExcelFile)
    
    Write-Status "Converting: $CsvFile" "Cyan"
    
    try {
        # Read CSV data
        $data = Import-Csv -Path $CsvFile
        
        if ($data.Count -eq 0) {
            Write-Status "No data found in CSV file: $CsvFile" "Yellow"
            return $false
        }
        
        Write-Status "Found $($data.Count) records" "Green"
        
        # Create Excel file with basic formatting
        $data | Export-Excel -Path $ExcelFile -AutoSize -TableStyle Medium2
        
        # Check if file was created
        if (Test-Path $ExcelFile) {
            Write-Status "Basic Excel file created: $ExcelFile" "Green"
            
            # Add color coding using COM object
            try {
                Write-Status "Adding color coding..." "Cyan"
                
                # Create Excel COM object
                $excel = New-Object -ComObject Excel.Application
                $excel.Visible = $false
                $excel.DisplayAlerts = $false
                
                # Open the Excel file
                $workbook = $excel.Workbooks.Open($ExcelFile)
                $worksheet = $workbook.Worksheets.Item(1)
                
                # Add color coding
                $row = 2  # Start from row 2 (skip header)
                foreach ($record in $data) {
                    if ($record.Status -eq "RED") {
                        # Color the entire row red
                        for ($col = 1; $col -le 20; $col++) {
                            $worksheet.Cells.Item($row, $col).Interior.Color = 255  # Light Red
                        }
                    } elseif ($record.Status -eq "YELLOW") {
                        # Color the entire row yellow
                        for ($col = 1; $col -le 20; $col++) {
                            $worksheet.Cells.Item($row, $col).Interior.Color = 65535  # Light Yellow
                        }
                    } elseif ($record.Status -eq "WHITE") {
                        # Color the entire row white
                        for ($col = 1; $col -le 20; $col++) {
                            $worksheet.Cells.Item($row, $col).Interior.Color = 16777215  # White
                        }
                    }
                    $row++
                }
                
                # Create Analysis Summary
                Write-Status "Creating analysis summary..." "Cyan"
                try {
                    # Add a new worksheet for analysis
                    $pivotWorksheet = $workbook.Worksheets.Add()
                    $pivotWorksheet.Name = "Analysis"
                    
                    # Add title
                    $pivotWorksheet.Cells.Item(1, 1) = "Windows Autorun Analysis Summary"
                    $pivotWorksheet.Cells.Item(1, 1).Font.Bold = $true
                    $pivotWorksheet.Cells.Item(1, 1).Font.Size = 14
                    
                    # Create summary statistics
                    $row = 3
                    $pivotWorksheet.Cells.Item($row, 1) = "Total Items:"
                    $pivotWorksheet.Cells.Item($row, 2) = $data.Count
                    $pivotWorksheet.Cells.Item($row, 1).Font.Bold = $true
                    $row++
                    
                    $pivotWorksheet.Cells.Item($row, 1) = "Suspicious (RED):"
                    $pivotWorksheet.Cells.Item($row, 2) = ($data | Where-Object { $_.Status -eq 'RED' }).Count
                    $pivotWorksheet.Cells.Item($row, 1).Font.Bold = $true
                    $row++
                    
                    $pivotWorksheet.Cells.Item($row, 1) = "After-market (YELLOW):"
                    $pivotWorksheet.Cells.Item($row, 2) = ($data | Where-Object { $_.Status -eq 'YELLOW' }).Count
                    $pivotWorksheet.Cells.Item($row, 1).Font.Bold = $true
                    $row++
                    
                    $pivotWorksheet.Cells.Item($row, 1) = "Baseline (WHITE):"
                    $pivotWorksheet.Cells.Item($row, 2) = ($data | Where-Object { $_.Status -eq 'WHITE' }).Count
                    $pivotWorksheet.Cells.Item($row, 1).Font.Bold = $true
                    $row += 3
                    
                    # Create Status breakdown table
                    $pivotWorksheet.Cells.Item($row, 1) = "Breakdown by Status:"
                    $pivotWorksheet.Cells.Item($row, 1).Font.Bold = $true
                    $pivotWorksheet.Cells.Item($row, 1).Font.Size = 12
                    $row++
                    
                    $pivotWorksheet.Cells.Item($row, 1) = "Status"
                    $pivotWorksheet.Cells.Item($row, 2) = "Count"
                    $pivotWorksheet.Cells.Item($row, 3) = "Percentage"
                    $pivotWorksheet.Range("A$row:C$row").Font.Bold = $true
                    $pivotWorksheet.Range("A$row:C$row").Interior.Color = 15773696  # Light blue
                    $row++
                    
                    $statusGroups = $data | Group-Object Status | Sort-Object Count -Descending
                    foreach ($group in $statusGroups) {
                        $percentage = [math]::Round(($group.Count / $data.Count) * 100, 1)
                        $pivotWorksheet.Cells.Item($row, 1) = $group.Name
                        $pivotWorksheet.Cells.Item($row, 2) = $group.Count
                        $pivotWorksheet.Cells.Item($row, 3) = "$percentage%"
                        $row++
                    }
                    $row += 2
                    
                    # Create Type breakdown table
                    $pivotWorksheet.Cells.Item($row, 1) = "Breakdown by Type:"
                    $pivotWorksheet.Cells.Item($row, 1).Font.Bold = $true
                    $pivotWorksheet.Cells.Item($row, 1).Font.Size = 12
                    $row++
                    
                    $pivotWorksheet.Cells.Item($row, 1) = "Type"
                    $pivotWorksheet.Cells.Item($row, 2) = "Count"
                    $pivotWorksheet.Cells.Item($row, 3) = "Percentage"
                    $pivotWorksheet.Range("A$row:C$row").Font.Bold = $true
                    $pivotWorksheet.Range("A$row:C$row").Interior.Color = 15773696  # Light blue
                    $row++
                    
                    $typeGroups = $data | Group-Object Type | Sort-Object Count -Descending
                    foreach ($group in $typeGroups) {
                        $percentage = [math]::Round(($group.Count / $data.Count) * 100, 1)
                        $pivotWorksheet.Cells.Item($row, 1) = $group.Name
                        $pivotWorksheet.Cells.Item($row, 2) = $group.Count
                        $pivotWorksheet.Cells.Item($row, 3) = "$percentage%"
                        $row++
                    }
                    $row += 2
                    
                    # Create User breakdown table
                    $pivotWorksheet.Cells.Item($row, 1) = "Breakdown by User:"
                    $pivotWorksheet.Cells.Item($row, 1).Font.Bold = $true
                    $pivotWorksheet.Cells.Item($row, 1).Font.Size = 12
                    $row++
                    
                    $pivotWorksheet.Cells.Item($row, 1) = "User"
                    $pivotWorksheet.Cells.Item($row, 2) = "Count"
                    $pivotWorksheet.Cells.Item($row, 3) = "Percentage"
                    $pivotWorksheet.Range("A$row:C$row").Font.Bold = $true
                    $pivotWorksheet.Range("A$row:C$row").Interior.Color = 15773696  # Light blue
                    $row++
                    
                    $userGroups = $data | Group-Object User | Sort-Object Count -Descending
                    foreach ($group in $userGroups) {
                        $percentage = [math]::Round(($group.Count / $data.Count) * 100, 1)
                        $pivotWorksheet.Cells.Item($row, 1) = $group.Name
                        $pivotWorksheet.Cells.Item($row, 2) = $group.Count
                        $pivotWorksheet.Cells.Item($row, 3) = "$percentage%"
                        $row++
                    }
                    $row += 2
                    
                    # Create Publisher breakdown table
                    $pivotWorksheet.Cells.Item($row, 1) = "Top Publishers:"
                    $pivotWorksheet.Cells.Item($row, 1).Font.Bold = $true
                    $pivotWorksheet.Cells.Item($row, 1).Font.Size = 12
                    $row++
                    
                    $pivotWorksheet.Cells.Item($row, 1) = "Publisher"
                    $pivotWorksheet.Cells.Item($row, 2) = "Count"
                    $pivotWorksheet.Cells.Item($row, 3) = "Percentage"
                    $pivotWorksheet.Range("A$row:C$row").Font.Bold = $true
                    $pivotWorksheet.Range("A$row:C$row").Interior.Color = 15773696  # Light blue
                    $row++
                    
                    $publisherGroups = $data | Where-Object { $_.Publisher -and $_.Publisher -ne "" } | Group-Object Publisher | Sort-Object Count -Descending | Select-Object -First 15
                    foreach ($group in $publisherGroups) {
                        $percentage = [math]::Round(($group.Count / $data.Count) * 100, 1)
                        $pivotWorksheet.Cells.Item($row, 1) = $group.Name
                        $pivotWorksheet.Cells.Item($row, 2) = $group.Count
                        $pivotWorksheet.Cells.Item($row, 3) = "$percentage%"
                        $row++
                    }
                    
                    # Auto-fit columns
                    $pivotWorksheet.UsedRange.Columns.AutoFit()
                    
                    Write-Status "Analysis summary created successfully" "Green"
                } catch {
                    Write-Status "Analysis summary creation failed: $($_.Exception.Message)" "Yellow"
                }
                
                # Save and close
                $workbook.Save()
                $workbook.Close()
                $excel.Quit()
                [System.Runtime.Interopservices.Marshal]::ReleaseComObject($excel) | Out-Null
                
                Write-Status "Excel file with color coding created successfully: $ExcelFile" "Green"
                return $true
                
            } catch {
                Write-Status "Color coding failed, but basic Excel file was created: $($_.Exception.Message)" "Yellow"
                Write-Status "Excel file saved without color coding: $ExcelFile" "Green"
                
                # Clean up COM objects if they exist
                try {
                    if ($workbook) { $workbook.Close() }
                    if ($excel) { 
                        $excel.Quit()
                        [System.Runtime.Interopservices.Marshal]::ReleaseComObject($excel) | Out-Null
                    }
                } catch {
                    # Ignore cleanup errors
                }
                return $true
            }
        } else {
            Write-Status "Excel file creation failed" "Red"
            return $false
        }
        
    } catch {
        Write-Status "Error converting CSV: $($_.Exception.Message)" "Red"
        return $false
    }
}

# Main execution
Write-Status "CSV to Excel Converter for Windows Autorun Analyzer" "Cyan"
Write-Status "===================================================" "Cyan"

# Check if ImportExcel module is available
if (-not (Test-ImportExcelModule)) {
    Write-Status "ImportExcel module not found. Installing..." "Yellow"
    try {
        Install-Module ImportExcel -Force -Scope CurrentUser
        Write-Status "ImportExcel module installed successfully" "Green"
    } catch {
        Write-Status "Failed to install ImportExcel module: $($_.Exception.Message)" "Red"
        Write-Status "Please install manually: Install-Module ImportExcel" "Yellow"
        exit 1
    }
}

# Validate input path
if (-not (Test-Path $CsvPath)) {
    Write-Status "Path not found: $CsvPath" "Red"
    exit 1
}

$processedFiles = 0
$successfulConversions = 0

# Determine if we're processing a single file or directory
if (Test-Path $CsvPath -PathType Leaf) {
    # Single file
    $csvFiles = @($CsvPath)
} else {
    # Directory - find CSV files
    if ($Recursive) {
        $csvFiles = Get-ChildItem -Path $CsvPath -Filter "*.csv" -Recurse | Select-Object -ExpandProperty FullName
    } else {
        $csvFiles = Get-ChildItem -Path $CsvPath -Filter "*.csv" | Select-Object -ExpandProperty FullName
    }
    
    if ($csvFiles.Count -eq 0) {
        Write-Status "No CSV files found in: $CsvPath" "Yellow"
        exit 0
    }
    
    Write-Status "Found $($csvFiles.Count) CSV files to process" "Cyan"
}

# Process each CSV file
foreach ($csvFile in $csvFiles) {
    $processedFiles++
    
    # Generate output path if not provided
    if ($OutputPath -and $csvFiles.Count -eq 1) {
        $excelFile = $OutputPath
    } else {
        $excelFile = $csvFile -replace '\.csv$', '.xlsx'
    }
    
    Write-Status "Processing file $processedFiles of $($csvFiles.Count): $(Split-Path $csvFile -Leaf)" "Cyan"
    
    if (Convert-CsvToExcel -CsvFile $csvFile -ExcelFile $excelFile) {
        $successfulConversions++
    }
    
    Write-Status "" "White"  # Empty line for readability
}

# Summary
Write-Status "Conversion Summary:" "Cyan"
Write-Status "==================" "Cyan"
Write-Status "Files processed: $processedFiles" "White"
Write-Status "Successful conversions: $successfulConversions" "Green"
Write-Status "Failed conversions: $($processedFiles - $successfulConversions)" "Red"

if ($successfulConversions -gt 0) {
    Write-Status "Conversion completed successfully!" "Green"
} else {
    Write-Status "No files were successfully converted." "Red"
    exit 1
}
